# Generated by Django 5.2.15 on 2026-06-13 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('denuncia', '0004_denuncia_cpf_denuncia_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('nivel_risco', models.CharField(choices=[('CR', 'Critico'), ('AL', 'Alto'), ('ME', 'Medio'), ('BA', 'Baixo')], max_length=2)),
                ('denuncia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='auditoria', to='denuncia.denuncia')),
            ],
        ),
    ]
