# Generated by Django 5.2.15 on 2026-06-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoriaadministrativa',
            old_name='nivel_risco',
            new_name='nivel_risco_corrigido',
        ),
    ]
