# Generated by Django 5.2.15 on 2026-06-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_endereco_lagradouro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoApp',
        ),
    ]
