# Generated by Django 5.2.15 on 2026-06-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agressor_mora_com_vitima', models.CharField(choices=[('SI', 'Sim'), ('NA', 'Não')], max_length=2)),
                ('agressor_possui_arma', models.CharField(choices=[('SI', 'Sim'), ('NA', 'Não')], max_length=2)),
                ('houve_ameaca_morte', models.CharField(choices=[('SI', 'Sim'), ('NA', 'Não')], max_length=2)),
                ('agressao_fisica_recente', models.CharField(choices=[('SI', 'Sim'), ('NA', 'Não')], max_length=2)),
                ('possui_medida_protetiva', models.CharField(choices=[('SI', 'Sim'), ('NA', 'Não')], max_length=2)),
                ('descumprimento_medida_protetiva', models.CharField(choices=[('SI', 'Sim'), ('NA', 'Não')], max_length=2)),
                ('ha_criancas_envolvidas', models.CharField(choices=[('SI', 'Sim'), ('NA', 'Não')], max_length=2)),
                ('humilhacoes_constantes', models.CharField(choices=[('NU', 'Nunca'), ('RA', 'Raramente'), ('FR', 'Frequentemente')], max_length=2)),
                ('relato_ocorrido', models.TextField()),
                ('observacoes_adicionais', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Opcao',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
    ]
