# Generated by Django 5.2.15 on 2026-06-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0002_questionario_delete_opcao_delete_pergunta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionario',
            old_name='observacoes_adicionais',
            new_name='caracteristicas_fisicas_autor',
        ),
        migrations.RenameField(
            model_name='questionario',
            old_name='relato_ocorrido',
            new_name='descricao_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='agressao_fisica_recente',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='agressor_mora_com_vitima',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='agressor_possui_arma',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='descumprimento_medida_protetiva',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='ha_criancas_envolvidas',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='houve_ameaca_morte',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='humilhacoes_constantes',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='possui_medida_protetiva',
        ),
        migrations.AddField(
            model_name='questionario',
            name='arma_ou_instrumento_utilizado',
            field=models.CharField(blank=True, choices=[('NE', 'Nenhum'), ('AF', 'Arma de fogo'), ('AB', 'Arma branca'), ('OC', 'Objeto contundente'), ('OU', 'Outro')], max_length=2),
        ),
        migrations.AddField(
            model_name='questionario',
            name='cor_veiculo_autor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='questionario',
            name='cpf_autor',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='questionario',
            name='cpf_vitima',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='questionario',
            name='data_nascimento_aproximada_autor',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='data_nascimento_vitima',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='email_vitima',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='questionario',
            name='endereco_conhecido_autor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='questionario',
            name='endereco_residencial_vitima',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='questionario',
            name='informacoes_testemunhas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='medida_protetiva_em_vigor',
            field=models.CharField(blank=True, choices=[('SI', 'Sim'), ('NA', 'Não'), ('NS', 'Não sei')], max_length=2),
        ),
        migrations.AddField(
            model_name='questionario',
            name='modelo_marca_veiculo_autor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questionario',
            name='nome_completo_autor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='questionario',
            name='nome_completo_vitima',
            field=models.CharField(default='calabresinho nao informou', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='objetos_subtraidos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='placa_veiculo_autor',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='questionario',
            name='telefone_vitima',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='questionario',
            name='tipo_veiculo_autor',
            field=models.CharField(blank=True, choices=[('CA', 'Carro'), ('MO', 'Moto'), ('CM', 'Caminhão'), ('ON', 'Ônibus'), ('OU', 'Outro')], max_length=2),
        ),
        migrations.AddField(
            model_name='questionario',
            name='violencia_recorrente',
            field=models.CharField(blank=True, choices=[('SI', 'Sim'), ('NA', 'Não'), ('NS', 'Não sei')], max_length=2),
        ),
        migrations.AddField(
            model_name='questionario',
            name='vitima_deseja_representar_criminalmente',
            field=models.CharField(blank=True, choices=[('SI', 'Sim'), ('NA', 'Não'), ('NS', 'Não sei')], max_length=2),
        ),
    ]
