# Generated by Django 5.2.15 on 2026-06-15 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0003_rename_observacoes_adicionais_questionario_caracteristicas_fisicas_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='data_nascimento_aproximada_autor',
        ),
        migrations.AddField(
            model_name='questionario',
            name='bairro_fato',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questionario',
            name='cidade_fato',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questionario',
            name='data_fato',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='estado_fato',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='questionario',
            name='ha_criancas_adolescentes_envolvidos',
            field=models.CharField(blank=True, choices=[('SI', 'Sim'), ('NA', 'Não')], max_length=2),
        ),
        migrations.AddField(
            model_name='questionario',
            name='ha_risco_integridade_fisica',
            field=models.CharField(blank=True, choices=[('SI', 'Sim'), ('NA', 'Não'), ('NS', 'Não sei')], max_length=2),
        ),
        migrations.AddField(
            model_name='questionario',
            name='hora_aproximada_fato',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='idade_aproximada_autor',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='logradouro_fato',
            field=models.CharField(default='Rua Calabreso', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='numero_fato',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='questionario',
            name='onde_ocorreu',
            field=models.CharField(choices=[('RV', 'Residência da vítima'), ('RA', 'Residência do autor'), ('RC', 'Residência comum'), ('VP', 'Via pública'), ('LT', 'Local de trabalho'), ('OU', 'Outro')], default='Nao informado', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='relacao_com_vitima',
            field=models.CharField(choices=[('CO', 'Cônjuge'), ('EC', 'Ex-cônjuge'), ('NA', 'Namorado(a)'), ('EN', 'Ex-namorado(a)'), ('FA', 'Familiar'), ('CN', 'Conhecido(a)'), ('DE', 'Desconhecido(a)')], default='CN', max_length=2),
            preserve_default=False,
        ),
    ]
