# Generated by Django 5.2.15 on 2026-06-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0009_remove_denunciabaseinfo_cpf_and_more'),
        ('questionario', '0004_remove_questionario_data_nascimento_aproximada_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='denuncia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='questionario', to='denuncia.denuncia'),
            preserve_default=False,
        ),
    ]
