# Generated by Django 5.2.15 on 2026-06-15 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0009_remove_denunciabaseinfo_cpf_and_more'),
        ('questionario', '0005_questionario_denuncia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='denuncia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='questionario', to='denuncia.denuncia'),
        ),
    ]
