# Generated by Django 5.2.15 on 2026-06-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0006_alter_questionario_denuncia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='arma_ou_instrumento_utilizado',
            field=models.CharField(blank=True, choices=[('NE', 'Nenhum'), ('AF', 'Arma de fogo'), ('AB', 'Arma branca'), ('OC', 'Objeto contundente'), ('OU', 'Outro')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='bairro_fato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='caracteristicas_fisicas_autor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='cidade_fato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='cor_veiculo_autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='cpf_autor',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='cpf_vitima',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='data_fato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='descricao_ocorrencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='email_vitima',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='endereco_conhecido_autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='endereco_residencial_vitima',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='estado_fato',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='ha_criancas_adolescentes_envolvidos',
            field=models.CharField(blank=True, choices=[('SI', 'Sim'), ('NA', 'Não')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='ha_risco_integridade_fisica',
            field=models.CharField(blank=True, choices=[('SI', 'Sim'), ('NA', 'Não'), ('NS', 'Não sei')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='informacoes_testemunhas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='medida_protetiva_em_vigor',
            field=models.CharField(blank=True, choices=[('SI', 'Sim'), ('NA', 'Não'), ('NS', 'Não sei')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='modelo_marca_veiculo_autor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='nome_completo_autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='numero_fato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='objetos_subtraidos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='onde_ocorreu',
            field=models.CharField(blank=True, choices=[('RV', 'Residência da vítima'), ('RA', 'Residência do autor'), ('RC', 'Residência comum'), ('VP', 'Via pública'), ('LT', 'Local de trabalho'), ('OU', 'Outro')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='placa_veiculo_autor',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='relacao_com_vitima',
            field=models.CharField(blank=True, choices=[('CO', 'Cônjuge'), ('EC', 'Ex-cônjuge'), ('NA', 'Namorado(a)'), ('EN', 'Ex-namorado(a)'), ('FA', 'Familiar'), ('CN', 'Conhecido(a)'), ('DE', 'Desconhecido(a)')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='telefone_vitima',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='tipo_veiculo_autor',
            field=models.CharField(blank=True, choices=[('CA', 'Carro'), ('MO', 'Moto'), ('CM', 'Caminhão'), ('ON', 'Ônibus'), ('OU', 'Outro')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='violencia_recorrente',
            field=models.CharField(blank=True, choices=[('SI', 'Sim'), ('NA', 'Não'), ('NS', 'Não sei')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='vitima_deseja_representar_criminalmente',
            field=models.CharField(blank=True, choices=[('SI', 'Sim'), ('NA', 'Não'), ('NS', 'Não sei')], max_length=2, null=True),
        ),
    ]
