# Generated by Django 5.2.15 on 2026-06-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0007_alter_questionario_arma_ou_instrumento_utilizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='nome_completo_vitima',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
