# Generated by Django 5.2.15 on 2026-06-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0008_alter_questionario_nome_completo_vitima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='ha_criancas_adolescentes_envolvidos',
            field=models.CharField(choices=[('SI', 'Sim'), ('NA', 'Não'), ('NS', 'Não sei')], default='NS', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='ha_risco_integridade_fisica',
            field=models.CharField(choices=[('SI', 'Sim'), ('NA', 'Não'), ('NS', 'Não sei')], default='NS', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='onde_ocorreu',
            field=models.CharField(choices=[('RV', 'Residência da vítima'), ('RA', 'Residência do autor'), ('RC', 'Residência comum'), ('VP', 'Via pública'), ('LT', 'Local de trabalho'), ('OU', 'Outro')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='relacao_com_vitima',
            field=models.CharField(choices=[('CO', 'Cônjuge'), ('EC', 'Ex-cônjuge'), ('NA', 'Namorado(a)'), ('EN', 'Ex-namorado(a)'), ('FA', 'Familiar'), ('CN', 'Conhecido(a)'), ('DE', 'Desconhecido(a)')], max_length=2, null=True),
        ),
    ]
