# Generated by Django 5.2.15 on 2026-06-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('codigo_denuncia', models.CharField(editable=False, max_length=40, unique=True)),
                ('nivel_risco', models.CharField(choices=[('CR', 'Critico'), ('AL', 'Alto'), ('ME', 'Medio'), ('BA', 'Baixo')], max_length=2)),
                ('status', models.CharField(max_length=2, verbose_name=[('RA', 'Rascunho'), ('SV', 'Salvo'), ('VA', 'Validada'), ('EC', 'Encaminhada'), ('FI', 'Finalizada')])),
            ],
        ),
    ]
