# Generated by Django 5.2.15 on 2026-06-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('RA', 'Rascunho'), ('SV', 'Salvo'), ('VA', 'Validada'), ('EC', 'Encaminhada'), ('FI', 'Finalizada')], max_length=2),
        ),
    ]
