# Generated by Django 5.2.15 on 2026-06-13 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('denuncia', '0002_alter_denuncia_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='denunciante_envolvida',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='endereco_denunciante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncia_d', to='core.endereco'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='endereco_vitima',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncia_v', to='core.endereco'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='registrou_anteriormente',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
