# Generated by Django 5.2.15 on 2026-06-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0003_denuncia_denunciante_envolvida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='situacao_anterior',
            field=models.CharField(blank=True, choices=[('EN', 'A ocorrência anterior foi encerrada'), ('AN', 'A ocorrência ainda está em andamento'), ('SC', 'Não tenho certeza')], max_length=2, null=True),
        ),
    ]
