# Generated by Django 5.2.15 on 2026-06-13 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('denuncia', '0004_denuncia_cpf_denuncia_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='denunciante_envolvida',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='endereco_denunciante',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='endereco_vitima',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='registrou_anteriormente',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='situacao_anterior',
        ),
        migrations.CreateModel(
            name='DenunciaBaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('registrou_anteriormente', models.BooleanField()),
                ('situacao_anterior', models.CharField(blank=True, choices=[('EN', 'A ocorrência anterior foi encerrada'), ('AN', 'A ocorrência ainda está em andamento'), ('SC', 'Não tenho certeza')], max_length=2, null=True)),
                ('denunciante_envolvida', models.BooleanField()),
                ('base_info', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='base_info', to='denuncia.denuncia')),
                ('endereco_denunciante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncia_d', to='core.endereco')),
                ('endereco_vitima', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncia_v', to='core.endereco')),
            ],
        ),
    ]
