# Generated by Django 5.2.15 on 2026-06-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0005_remove_denuncia_cpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncia',
            old_name='nivel_risco',
            new_name='risco_automatico',
        ),
    ]
