# Generated by Django 5.2.15 on 2026-06-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0006_rename_nivel_risco_denuncia_risco_automatico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denunciabaseinfo',
            old_name='base_info',
            new_name='denuncia',
        ),
    ]
