# Generated by Django 5.2.15 on 2026-06-13 23:18

import denuncia.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0007_rename_base_info_denunciabaseinfo_denuncia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=denuncia.models.upload_evidencia)),
                ('descricao', models.TextField(blank=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='denuncia.denuncia')),
            ],
        ),
    ]
