# Generated by Django 5.2.15 on 2026-06-14 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('denuncia', '0008_evidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denunciabaseinfo',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='denunciabaseinfo',
            name='endereco_denunciante',
        ),
        migrations.RemoveField(
            model_name='denunciabaseinfo',
            name='endereco_vitima',
        ),
        migrations.RemoveField(
            model_name='denunciabaseinfo',
            name='nome',
        ),
        migrations.AddField(
            model_name='denunciabaseinfo',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncia', to='core.endereco'),
        ),
        migrations.AddField(
            model_name='denunciabaseinfo',
            name='perigo_imediato',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='risco_automatico',
            field=models.CharField(blank=True, choices=[('CR', 'Critico'), ('AL', 'Alto'), ('ME', 'Medio'), ('BA', 'Baixo')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('RA', 'Rascunho'), ('SV', 'Salvo'), ('VA', 'Validada'), ('EC', 'Encaminhada'), ('FI', 'Finalizada')], default='RA', max_length=2),
        ),
        migrations.AlterField(
            model_name='denunciabaseinfo',
            name='situacao_anterior',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
