# Generated by Django 5.2.15 on 2026-06-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0009_remove_denunciabaseinfo_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencia',
            name='descricao',
        ),
    ]
