# Generated by Django 5.2.15 on 2026-06-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0010_remove_evidencia_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='risco_automatico',
        ),
    ]
